# Generated by Django 4.1.3 on 2025-01-15 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplybooksserverapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uid',
        ),
    ]
